### ISSUE TITLE
Talk links not working

### ISSUE THREAD

**Issue by ErikCohenDev** [rupl/frontend-testing#3]
Getting 404 for all the links to the talks in the readme. Could you please update the links?

**Comment by rupl** [comment]
Those are conference sites out of my control and it's quite possible they removed the content.

**Comment by rupl** [comment]
ok two of them were statically archived and the d.o folks could probably fix it by appending the file extension but I'll update the readme. Frontend United seems to have chosen not to archive content and it is lost.
